sudo: true
language: python
sudo: required
python:
- 2.7
cache: pip
install:
- sudo apt-get install -y -q python-dev python-pip
- pip install codecov
- pip install cov-core
- pip install nose2
- pip install git+https://github.com/dgnorth/drift-config@develop
- pip install uwsgi
script:
 - coverage run -m pytest
after_success:
 - codecov
 - coverage report
