sudo: true
language: python
sudo: required
python:
- 2.7
cache: pip
addons:
  apt:
    packages:
    - nginx

before_install:
- sudo chown $(whoami) /usr/share/nginx
- sudo chown $(whoami) /etc/nginx/nginx.conf

install:
- pip install pipenv
- pipenv install --dev --deploy

script:
- pytest --cov

after_success:
 - codecov
 - coverage report
