sudo: true
language: python
sudo: required

python:
  - 3.6

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - AWS_DEFAULT_OUTPUT=json
  matrix:
    - DRIFT_CONFIG_URL=s3://relib-test/directive-games

cache: pip
addons:
  apt:
    packages:
    - nginx

before_install:
  - sudo chown $(whoami) /usr/share/nginx
  - sudo chown $(whoami) /etc/nginx/nginx.conf
  - export BOTO_CONFIG=/dev/null
install:
  - pip install pipenv==2018.10.13
  - pipenv install --dev --deploy

script:
  - pytest --cov

after_success:
 - codecov
 - coverage report
 - pip install -e "git+https://github.com/dgnorth/drift.git#egg=drift[aws]"
 - drift-admin ami bake --skipcopy
 - drift-admin ami run
