sudo: true
language: python
sudo: required
python:
- 3.6
cache: pip
addons:
  apt:
    packages:
    - nginx

before_install:
- sudo chown $(whoami) /usr/share/nginx
- sudo chown $(whoami) /etc/nginx/nginx.conf

install:
- pip install pipenv==2018.10.13
- pipenv install --dev --deploy

script:
- pytest --cov

env:
  - DRIFT_CONFIG_URL=s3://relib-test/directive-games
  - DRIFT_TIER=DEVNORTH

after_success:
 - codecov
 - coverage report
 - pip install -e "git+https://github.com/dgnorth/drift.git#egg=drift[aws]"
 - drift-admin ami bake
